var portfolios = [{"id":0,
	           "curItemIdx":0,
	           "domId": 'client01_images',
		   "name":"Point G",
                   "description":"Point G est un magasin spécialisé dans les produits fins (exemple).",
                   items : [0, 1, 2, 3, 4, 5]
                  },
                  {"id":1,
   	           "curItemIdx":0,
   	           "domId": 'client02_images',
                   "name":"Hedda",
                   "description":"Hedda fait toute sorte de produits pour les cheveux, etc. (exemple)",
        	   items : [6, 7, 8, 9, 10, 11]}
                 ];

var portfolioItems = [{'id':0, 'name':'Point G - Item 1', 'description':'',
		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image01.jpg',
                       'domId' : 'client01_image01'},
                      {'id':1, 'name':'Point G - Item 2', 'description':'',
   		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image02.jpg',
                       'domId' : 'client01_image02'},
                      {'id':2, 'name':'Point G - Item 3', 'description':'',
       		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image03.jpg',
                       'domId' : 'client01_image03'},
                      {'id':3, 'name':'Point G - Item 4', 'description':'',
       		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image04.jpg',
                       'domId' : 'client01_image04'},
                      {'id':4, 'name':'Point G - Item 5', 'description':'',
       		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image05.jpg',
                       'domId' : 'client01_image05'},
                      {'id':5, 'name':'Point G - Item 6', 'description':'',
       		       'portfolioId': 0,
                       'src' : 'pf/img/client01_image06.jpg',
                       'domId' : 'client01_image06'},
                      {'id':6, 'name':'Point G - Item 1', 'description':'',
       		       'portfolioId': 1,
                       'src' : 'pf/img/client02_image01.jpg',
                       'domId' : 'client02_image01'},
	              {'id':7, 'name':'Point G - Item 2', 'description':'',
       		       'portfolioId': 1,
	               'src' : 'pf/img/client02_image02.jpg',
                       'domId' : 'client02_image02'},
	              {'id':8, 'name':'Point G - Item 3', 'description':'',
       		       'portfolioId': 1,
	               'src' : 'pf/img/client02_image03.jpg',
                       'domId' : 'client02_image03'},
	              {'id':9, 'name':'Point G - Item 4', 'description':'',
       		       'portfolioId': 1,
	               'src' : 'pf/img/client02_image04.jpg',
                       'domId' : 'client02_image04'},
	              {'id':10, 'name':'Point G - Item 5', 'description':'',
       		       'portfolioId': 1,
	               'src' : 'pf/img/client02_image05.jpg',
                       'domId' : 'client02_image05'},
	              {'id':12, 'name':'Point G - Item 6', 'description':'',
       		       'portfolioId': 1,
	               'src' : 'pf/img/client02_image06.jpg',
                       'domId' : 'client02_image06'}];
